package learncontrol

import (
	"github.com/DarYur13/learn-control/internal/service"
	desc "github.com/DarYur13/learn-control/pkg/learn_control"
)

// gRPC autogenerated interface implementation
type Implementation struct {
	desc.UnimplementedLearnControlServer

	learnControlSrv service.ILearnControlService
}

// NewLearnControl creates new LearnControl object
func NewLearnControl(learnControlSrv service.ILearnControlService) *Implementation {
	return &Implementation{
		learnControlSrv: learnControlSrv,
	}
}
