version: '3.8'

services:
  postgres:
    image: postgres:14-alpine3.15
    container_name: "learn_control_pg"
    environment:
      - "POSTGRES_DB=learn_control"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
  
  minio:
    image: quay.io/minio/minio
    container_name: "learn_control_minio"
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=supersecret"
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Web UI
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9090"

  # goose:
  #   build: ./migrations/
  #   restart: on-failure
  #   environment:
  #     DB_HOST: postgres
  #   ports:
  #     - "5444:5432"
  #   depends_on:
  #     - postgres

  # app:
  #   build: .
  #   ports:
  #     - "50051:50051"
  #     - "8000:8000"
  #   depends_on:
  #     - postgres