// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: learn_control.proto

package learn_control

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetEmployeesByNameRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEmployeesByNameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEmployeesByNameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEmployeesByNameRequestMultiError, or nil if none found.
func (m *GetEmployeesByNameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEmployeesByNameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetEmployeesByNameRequestMultiError(errors)
	}

	return nil
}

// GetEmployeesByNameRequestMultiError is an error wrapping multiple validation
// errors returned by GetEmployeesByNameRequest.ValidateAll() if the
// designated constraints aren't met.
type GetEmployeesByNameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEmployeesByNameRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEmployeesByNameRequestMultiError) AllErrors() []error { return m }

// GetEmployeesByNameRequestValidationError is the validation error returned by
// GetEmployeesByNameRequest.Validate if the designated constraints aren't met.
type GetEmployeesByNameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEmployeesByNameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEmployeesByNameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEmployeesByNameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEmployeesByNameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEmployeesByNameRequestValidationError) ErrorName() string {
	return "GetEmployeesByNameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEmployeesByNameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEmployeesByNameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEmployeesByNameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEmployeesByNameRequestValidationError{}

// Validate checks the field values on GetEmployeesByNameResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEmployeesByNameResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEmployeesByNameResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEmployeesByNameResponseMultiError, or nil if none found.
func (m *GetEmployeesByNameResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEmployeesByNameResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEmployees() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetEmployeesByNameResponseValidationError{
						field:  fmt.Sprintf("Employees[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetEmployeesByNameResponseValidationError{
						field:  fmt.Sprintf("Employees[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetEmployeesByNameResponseValidationError{
					field:  fmt.Sprintf("Employees[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetEmployeesByNameResponseMultiError(errors)
	}

	return nil
}

// GetEmployeesByNameResponseMultiError is an error wrapping multiple
// validation errors returned by GetEmployeesByNameResponse.ValidateAll() if
// the designated constraints aren't met.
type GetEmployeesByNameResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEmployeesByNameResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEmployeesByNameResponseMultiError) AllErrors() []error { return m }

// GetEmployeesByNameResponseValidationError is the validation error returned
// by GetEmployeesByNameResponse.Validate if the designated constraints aren't met.
type GetEmployeesByNameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEmployeesByNameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEmployeesByNameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEmployeesByNameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEmployeesByNameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEmployeesByNameResponseValidationError) ErrorName() string {
	return "GetEmployeesByNameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetEmployeesByNameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEmployeesByNameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEmployeesByNameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEmployeesByNameResponseValidationError{}

// Validate checks the field values on EmployeeBaseInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EmployeeBaseInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeBaseInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EmployeeBaseInfoMultiError, or nil if none found.
func (m *EmployeeBaseInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeBaseInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Fullname

	// no validation rules for Birthdate

	if len(errors) > 0 {
		return EmployeeBaseInfoMultiError(errors)
	}

	return nil
}

// EmployeeBaseInfoMultiError is an error wrapping multiple validation errors
// returned by EmployeeBaseInfo.ValidateAll() if the designated constraints
// aren't met.
type EmployeeBaseInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeBaseInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeBaseInfoMultiError) AllErrors() []error { return m }

// EmployeeBaseInfoValidationError is the validation error returned by
// EmployeeBaseInfo.Validate if the designated constraints aren't met.
type EmployeeBaseInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeBaseInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeBaseInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeBaseInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeBaseInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeBaseInfoValidationError) ErrorName() string { return "EmployeeBaseInfoValidationError" }

// Error satisfies the builtin error interface
func (e EmployeeBaseInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeBaseInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeBaseInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeBaseInfoValidationError{}

// Validate checks the field values on GetEmployeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEmployeeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEmployeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEmployeeRequestMultiError, or nil if none found.
func (m *GetEmployeeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEmployeeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetEmployeeRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetEmployeeRequestMultiError(errors)
	}

	return nil
}

// GetEmployeeRequestMultiError is an error wrapping multiple validation errors
// returned by GetEmployeeRequest.ValidateAll() if the designated constraints
// aren't met.
type GetEmployeeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEmployeeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEmployeeRequestMultiError) AllErrors() []error { return m }

// GetEmployeeRequestValidationError is the validation error returned by
// GetEmployeeRequest.Validate if the designated constraints aren't met.
type GetEmployeeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEmployeeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEmployeeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEmployeeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEmployeeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEmployeeRequestValidationError) ErrorName() string {
	return "GetEmployeeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEmployeeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEmployeeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEmployeeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEmployeeRequestValidationError{}

// Validate checks the field values on GetEmployeeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEmployeeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEmployeeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEmployeeResponseMultiError, or nil if none found.
func (m *GetEmployeeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEmployeeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Fullname

	// no validation rules for Birthdate

	// no validation rules for Department

	// no validation rules for Position

	// no validation rules for Snils

	for idx, item := range m.GetTrainings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetEmployeeResponseValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetEmployeeResponseValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetEmployeeResponseValidationError{
					field:  fmt.Sprintf("Trainings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetEmployeeResponseMultiError(errors)
	}

	return nil
}

// GetEmployeeResponseMultiError is an error wrapping multiple validation
// errors returned by GetEmployeeResponse.ValidateAll() if the designated
// constraints aren't met.
type GetEmployeeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEmployeeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEmployeeResponseMultiError) AllErrors() []error { return m }

// GetEmployeeResponseValidationError is the validation error returned by
// GetEmployeeResponse.Validate if the designated constraints aren't met.
type GetEmployeeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEmployeeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEmployeeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEmployeeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEmployeeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEmployeeResponseValidationError) ErrorName() string {
	return "GetEmployeeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetEmployeeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEmployeeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEmployeeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEmployeeResponseValidationError{}

// Validate checks the field values on Training with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Training) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Training with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TrainingMultiError, or nil
// if none found.
func (m *Training) ValidateAll() error {
	return m.validate(true)
}

func (m *Training) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for PassDate

	// no validation rules for RePassDate

	if len(errors) > 0 {
		return TrainingMultiError(errors)
	}

	return nil
}

// TrainingMultiError is an error wrapping multiple validation errors returned
// by Training.ValidateAll() if the designated constraints aren't met.
type TrainingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrainingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrainingMultiError) AllErrors() []error { return m }

// TrainingValidationError is the validation error returned by
// Training.Validate if the designated constraints aren't met.
type TrainingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrainingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrainingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrainingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrainingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrainingValidationError) ErrorName() string { return "TrainingValidationError" }

// Error satisfies the builtin error interface
func (e TrainingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTraining.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrainingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrainingValidationError{}

// Validate checks the field values on SetEmployeeTrainingDateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetEmployeeTrainingDateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetEmployeeTrainingDateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SetEmployeeTrainingDateRequestMultiError, or nil if none found.
func (m *SetEmployeeTrainingDateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetEmployeeTrainingDateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EmployeeID

	// no validation rules for TrainigID

	// no validation rules for Date

	if len(errors) > 0 {
		return SetEmployeeTrainingDateRequestMultiError(errors)
	}

	return nil
}

// SetEmployeeTrainingDateRequestMultiError is an error wrapping multiple
// validation errors returned by SetEmployeeTrainingDateRequest.ValidateAll()
// if the designated constraints aren't met.
type SetEmployeeTrainingDateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetEmployeeTrainingDateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetEmployeeTrainingDateRequestMultiError) AllErrors() []error { return m }

// SetEmployeeTrainingDateRequestValidationError is the validation error
// returned by SetEmployeeTrainingDateRequest.Validate if the designated
// constraints aren't met.
type SetEmployeeTrainingDateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetEmployeeTrainingDateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetEmployeeTrainingDateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetEmployeeTrainingDateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetEmployeeTrainingDateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetEmployeeTrainingDateRequestValidationError) ErrorName() string {
	return "SetEmployeeTrainingDateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetEmployeeTrainingDateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetEmployeeTrainingDateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetEmployeeTrainingDateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetEmployeeTrainingDateRequestValidationError{}

// Validate checks the field values on SetEmployeeTrainingDateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetEmployeeTrainingDateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetEmployeeTrainingDateResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SetEmployeeTrainingDateResponseMultiError, or nil if none found.
func (m *SetEmployeeTrainingDateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetEmployeeTrainingDateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PassDate

	// no validation rules for RePassDate

	if len(errors) > 0 {
		return SetEmployeeTrainingDateResponseMultiError(errors)
	}

	return nil
}

// SetEmployeeTrainingDateResponseMultiError is an error wrapping multiple
// validation errors returned by SetEmployeeTrainingDateResponse.ValidateAll()
// if the designated constraints aren't met.
type SetEmployeeTrainingDateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetEmployeeTrainingDateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetEmployeeTrainingDateResponseMultiError) AllErrors() []error { return m }

// SetEmployeeTrainingDateResponseValidationError is the validation error
// returned by SetEmployeeTrainingDateResponse.Validate if the designated
// constraints aren't met.
type SetEmployeeTrainingDateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetEmployeeTrainingDateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetEmployeeTrainingDateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetEmployeeTrainingDateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetEmployeeTrainingDateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetEmployeeTrainingDateResponseValidationError) ErrorName() string {
	return "SetEmployeeTrainingDateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetEmployeeTrainingDateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetEmployeeTrainingDateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetEmployeeTrainingDateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetEmployeeTrainingDateResponseValidationError{}

// Validate checks the field values on UpdateEmployeeTrainingDateRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateEmployeeTrainingDateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateEmployeeTrainingDateRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateEmployeeTrainingDateRequestMultiError, or nil if none found.
func (m *UpdateEmployeeTrainingDateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateEmployeeTrainingDateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EmployeeID

	// no validation rules for TrainigID

	// no validation rules for Date

	if len(errors) > 0 {
		return UpdateEmployeeTrainingDateRequestMultiError(errors)
	}

	return nil
}

// UpdateEmployeeTrainingDateRequestMultiError is an error wrapping multiple
// validation errors returned by
// UpdateEmployeeTrainingDateRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateEmployeeTrainingDateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateEmployeeTrainingDateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateEmployeeTrainingDateRequestMultiError) AllErrors() []error { return m }

// UpdateEmployeeTrainingDateRequestValidationError is the validation error
// returned by UpdateEmployeeTrainingDateRequest.Validate if the designated
// constraints aren't met.
type UpdateEmployeeTrainingDateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateEmployeeTrainingDateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateEmployeeTrainingDateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateEmployeeTrainingDateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateEmployeeTrainingDateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateEmployeeTrainingDateRequestValidationError) ErrorName() string {
	return "UpdateEmployeeTrainingDateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateEmployeeTrainingDateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateEmployeeTrainingDateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateEmployeeTrainingDateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateEmployeeTrainingDateRequestValidationError{}

// Validate checks the field values on UpdateEmployeeTrainingDateResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateEmployeeTrainingDateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateEmployeeTrainingDateResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateEmployeeTrainingDateResponseMultiError, or nil if none found.
func (m *UpdateEmployeeTrainingDateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateEmployeeTrainingDateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PassDate

	// no validation rules for RePassDate

	if len(errors) > 0 {
		return UpdateEmployeeTrainingDateResponseMultiError(errors)
	}

	return nil
}

// UpdateEmployeeTrainingDateResponseMultiError is an error wrapping multiple
// validation errors returned by
// UpdateEmployeeTrainingDateResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateEmployeeTrainingDateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateEmployeeTrainingDateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateEmployeeTrainingDateResponseMultiError) AllErrors() []error { return m }

// UpdateEmployeeTrainingDateResponseValidationError is the validation error
// returned by UpdateEmployeeTrainingDateResponse.Validate if the designated
// constraints aren't met.
type UpdateEmployeeTrainingDateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateEmployeeTrainingDateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateEmployeeTrainingDateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateEmployeeTrainingDateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateEmployeeTrainingDateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateEmployeeTrainingDateResponseValidationError) ErrorName() string {
	return "UpdateEmployeeTrainingDateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateEmployeeTrainingDateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateEmployeeTrainingDateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateEmployeeTrainingDateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateEmployeeTrainingDateResponseValidationError{}

// Validate checks the field values on GetFiltersRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetFiltersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFiltersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFiltersRequestMultiError, or nil if none found.
func (m *GetFiltersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFiltersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetFiltersRequestMultiError(errors)
	}

	return nil
}

// GetFiltersRequestMultiError is an error wrapping multiple validation errors
// returned by GetFiltersRequest.ValidateAll() if the designated constraints
// aren't met.
type GetFiltersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFiltersRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFiltersRequestMultiError) AllErrors() []error { return m }

// GetFiltersRequestValidationError is the validation error returned by
// GetFiltersRequest.Validate if the designated constraints aren't met.
type GetFiltersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFiltersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFiltersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFiltersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFiltersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFiltersRequestValidationError) ErrorName() string {
	return "GetFiltersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFiltersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFiltersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFiltersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFiltersRequestValidationError{}

// Validate checks the field values on GetFiltersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFiltersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFiltersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFiltersResponseMultiError, or nil if none found.
func (m *GetFiltersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFiltersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTrainings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetFiltersResponseValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetFiltersResponseValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetFiltersResponseValidationError{
					field:  fmt.Sprintf("Trainings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetFiltersResponseMultiError(errors)
	}

	return nil
}

// GetFiltersResponseMultiError is an error wrapping multiple validation errors
// returned by GetFiltersResponse.ValidateAll() if the designated constraints
// aren't met.
type GetFiltersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFiltersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFiltersResponseMultiError) AllErrors() []error { return m }

// GetFiltersResponseValidationError is the validation error returned by
// GetFiltersResponse.Validate if the designated constraints aren't met.
type GetFiltersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFiltersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFiltersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFiltersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFiltersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFiltersResponseValidationError) ErrorName() string {
	return "GetFiltersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetFiltersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFiltersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFiltersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFiltersResponseValidationError{}

// Validate checks the field values on TrainingBaseInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TrainingBaseInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrainingBaseInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrainingBaseInfoMultiError, or nil if none found.
func (m *TrainingBaseInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TrainingBaseInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return TrainingBaseInfoMultiError(errors)
	}

	return nil
}

// TrainingBaseInfoMultiError is an error wrapping multiple validation errors
// returned by TrainingBaseInfo.ValidateAll() if the designated constraints
// aren't met.
type TrainingBaseInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrainingBaseInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrainingBaseInfoMultiError) AllErrors() []error { return m }

// TrainingBaseInfoValidationError is the validation error returned by
// TrainingBaseInfo.Validate if the designated constraints aren't met.
type TrainingBaseInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrainingBaseInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrainingBaseInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrainingBaseInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrainingBaseInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrainingBaseInfoValidationError) ErrorName() string { return "TrainingBaseInfoValidationError" }

// Error satisfies the builtin error interface
func (e TrainingBaseInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrainingBaseInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrainingBaseInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrainingBaseInfoValidationError{}

// Validate checks the field values on GetEmployeesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEmployeesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEmployeesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEmployeesRequestMultiError, or nil if none found.
func (m *GetEmployeesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEmployeesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.DepartmentID != nil {
		// no validation rules for DepartmentID
	}

	if m.PositionID != nil {
		// no validation rules for PositionID
	}

	if m.TrainingID != nil {
		// no validation rules for TrainingID
	}

	if m.RetrainingIn != nil {
		// no validation rules for RetrainingIn
	}

	if m.TrainigsPassed != nil {
		// no validation rules for TrainigsPassed
	}

	if len(errors) > 0 {
		return GetEmployeesRequestMultiError(errors)
	}

	return nil
}

// GetEmployeesRequestMultiError is an error wrapping multiple validation
// errors returned by GetEmployeesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetEmployeesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEmployeesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEmployeesRequestMultiError) AllErrors() []error { return m }

// GetEmployeesRequestValidationError is the validation error returned by
// GetEmployeesRequest.Validate if the designated constraints aren't met.
type GetEmployeesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEmployeesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEmployeesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEmployeesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEmployeesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEmployeesRequestValidationError) ErrorName() string {
	return "GetEmployeesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEmployeesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEmployeesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEmployeesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEmployeesRequestValidationError{}

// Validate checks the field values on GetEmployeesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEmployeesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEmployeesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEmployeesResponseMultiError, or nil if none found.
func (m *GetEmployeesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEmployeesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEmployees() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetEmployeesResponseValidationError{
						field:  fmt.Sprintf("Employees[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetEmployeesResponseValidationError{
						field:  fmt.Sprintf("Employees[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetEmployeesResponseValidationError{
					field:  fmt.Sprintf("Employees[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetEmployeesResponseMultiError(errors)
	}

	return nil
}

// GetEmployeesResponseMultiError is an error wrapping multiple validation
// errors returned by GetEmployeesResponse.ValidateAll() if the designated
// constraints aren't met.
type GetEmployeesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEmployeesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEmployeesResponseMultiError) AllErrors() []error { return m }

// GetEmployeesResponseValidationError is the validation error returned by
// GetEmployeesResponse.Validate if the designated constraints aren't met.
type GetEmployeesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEmployeesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEmployeesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEmployeesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEmployeesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEmployeesResponseValidationError) ErrorName() string {
	return "GetEmployeesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetEmployeesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEmployeesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEmployeesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEmployeesResponseValidationError{}

// Validate checks the field values on EmployeeInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EmployeeInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmployeeInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmployeeInfoMultiError, or
// nil if none found.
func (m *EmployeeInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *EmployeeInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Fullname

	// no validation rules for Department

	// no validation rules for Position

	for idx, item := range m.GetTrainings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EmployeeInfoValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EmployeeInfoValidationError{
						field:  fmt.Sprintf("Trainings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EmployeeInfoValidationError{
					field:  fmt.Sprintf("Trainings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return EmployeeInfoMultiError(errors)
	}

	return nil
}

// EmployeeInfoMultiError is an error wrapping multiple validation errors
// returned by EmployeeInfo.ValidateAll() if the designated constraints aren't met.
type EmployeeInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmployeeInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmployeeInfoMultiError) AllErrors() []error { return m }

// EmployeeInfoValidationError is the validation error returned by
// EmployeeInfo.Validate if the designated constraints aren't met.
type EmployeeInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmployeeInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmployeeInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmployeeInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmployeeInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmployeeInfoValidationError) ErrorName() string { return "EmployeeInfoValidationError" }

// Error satisfies the builtin error interface
func (e EmployeeInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmployeeInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmployeeInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmployeeInfoValidationError{}
